module.exports = {
    JOIN_T: "JOINING_NETWORK",
    JOINR_T: "JOINING_NETWORK_RELAY",
    ROUTING_T: "ROUTING_INFO",
    LEAVING_T: "LEAVING_NETWORK",
    INDEX_T: "INDEX",
    SEARCH_T: "SEARCH",
    SEARCHR_T: "SEARCH_RESPONSE",
    PING_T: "PING",
    ACK_T: "ACK"
}
